# Generated by Django 4.1 on 2023-11-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombrec', models.TextField(verbose_name='Nombre Categoria')),
                ('crea', models.DateTimeField(auto_now_add=True)),
                ('upda', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreE', models.TextField(verbose_name='Nombre Estacion')),
            ],
            options={
                'verbose_name': 'Estacion',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombrez', models.TextField(verbose_name='Descripcion')),
                ('imgenz', models.ImageField(upload_to='projects', verbose_name='imagen')),
                ('precioz', models.PositiveIntegerField(verbose_name='Precio del Producto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('catego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicar.categoria')),
            ],
            options={
                'verbose_name': 'Zapato',
                'verbose_name_plural': 'Zapatos',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='categoria',
            name='estacionc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicar.estacion'),
        ),
    ]
