# Generated by Django 4.1 on 2023-11-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicar', '0002_categoria_estacion_zapato_delete_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapato',
            old_name='imgenz',
            new_name='imgend',
        ),
        migrations.AlterField(
            model_name='zapato',
            name='Nombrez',
            field=models.TextField(verbose_name='Nombre'),
        ),
    ]
