# Generated by Django 4.1 on 2023-11-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicar', '0003_rename_imgenz_zapato_imgend_alter_zapato_nombrez'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='gene',
            field=models.CharField(blank=True, choices=[{'Masculino', 'Masculino '}, {'Femenino', 'Femenino '}], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='imgend',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='imagen'),
        ),
    ]
