# Generated by Django 4.1 on 2023-11-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicar', '0004_zapato_gene_alter_zapato_imgend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapato',
            name='description',
        ),
    ]
